### ISSUE TITLE
Reproduction

### ISSUE THREAD

**Issue by seongwn** [jxhuang0508/CaCo#4]
Hello, thank you for your great works.

I cannot reproduce your reported performance with the following command

![image](https://user-images.githubusercontent.com/37448491/209437848-4167ecb4-4169-4613-8afe-414aca7f6fb9.png)

![image](https://user-images.githubusercontent.com/37448491/209437766-ccc4e22a-6d71-4de3-8cea-93ad08a6b89b.png)
Is the above result in the second row(CaCo-S: 46.8 / CaCo-T: 48.3 / CaCo: 49.2) the results of warm-up stage?

I also want to know training details. 

Thank you very much.

**Comment by jxhuang0508** [comment]
Hi,

Thanks for your interests.

If you want to train/reproduce CaCo + ProDA (~58 mIoU), please following and complete all the steps (Step 1- 4).
According to the provided screenshot, it seems only step 1 (warmup) is completed.

If you want to train/reproduce CaCo (~50 mIoU), please following and complete the steps under "To train CaCo (~50 mIoU)".

Thanks.

**Comment by seongwn** [comment]
Thank you very much :)
