### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by seongwn** [jxhuang0508/CaCo#6]
Hello, thanks for your amazing work!

I wonder if the 'caco_stage1.pth' is the best result or the last result of warm-up stage (i.e. results of 120K iterations).

Thank you very much.

**Comment by jxhuang0508** [comment]
Hi,

Following previous works, the best model of the previous stage is used as the initial model or to generate initial pseudo labels, for the next training stage.

Thanks.

**Comment by seongwn** [comment]
Thank you very much. You've been a great help.
